id: I82011D02
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:23:20.727961'
last_modified: '2022-06-18T22:23:20.727978'
parser: null
source_metadata:
  title: Jam dbyangs bsod nams rgyal mtshans (1563–1617) Sakya Genealogy
  author: jam dbyangs bsod nams rgyal mtshan/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2018-09-06); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Lobsang Gyaltsen, Dharamsala (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2303
  bases:
    df3f:
      title: Jam dbyangs bsod nams rgyal mtshans (1563–1617) Sakya Genealogy
      order: 1
      base_file: df3f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
